// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Profiler.proto

package com.ugcs.ucs.proto;

public final class ProfilerProto {
  private ProfilerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ActionSummaryOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string actionType = 1;
    boolean hasActionType();
    String getActionType();
    
    // required int64 count = 2;
    boolean hasCount();
    long getCount();
    
    // required int64 errorCount = 3;
    boolean hasErrorCount();
    long getErrorCount();
    
    // required int64 activeCount = 4;
    boolean hasActiveCount();
    long getActiveCount();
    
    // required int64 minTime = 5;
    boolean hasMinTime();
    long getMinTime();
    
    // required int64 maxTime = 6;
    boolean hasMaxTime();
    long getMaxTime();
    
    // required int64 avgTime = 7;
    boolean hasAvgTime();
    long getAvgTime();
    
    // required int64 firstStartTimeMillis = 8;
    boolean hasFirstStartTimeMillis();
    long getFirstStartTimeMillis();
    
    // required int64 lastStopTimeMillis = 9;
    boolean hasLastStopTimeMillis();
    long getLastStopTimeMillis();
  }
  public static final class ActionSummary extends
      com.google.protobuf.GeneratedMessage
      implements ActionSummaryOrBuilder {
    // Use ActionSummary.newBuilder() to construct.
    private ActionSummary(Builder builder) {
      super(builder);
    }
    private ActionSummary(boolean noInit) {}
    
    private static final ActionSummary defaultInstance;
    public static ActionSummary getDefaultInstance() {
      return defaultInstance;
    }
    
    public ActionSummary getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ugcs.ucs.proto.ProfilerProto.internal_static_ActionSummary_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ugcs.ucs.proto.ProfilerProto.internal_static_ActionSummary_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string actionType = 1;
    public static final int ACTIONTYPE_FIELD_NUMBER = 1;
    private java.lang.Object actionType_;
    public boolean hasActionType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getActionType() {
      java.lang.Object ref = actionType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          actionType_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getActionTypeBytes() {
      java.lang.Object ref = actionType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        actionType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int64 count = 2;
    public static final int COUNT_FIELD_NUMBER = 2;
    private long count_;
    public boolean hasCount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getCount() {
      return count_;
    }
    
    // required int64 errorCount = 3;
    public static final int ERRORCOUNT_FIELD_NUMBER = 3;
    private long errorCount_;
    public boolean hasErrorCount() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getErrorCount() {
      return errorCount_;
    }
    
    // required int64 activeCount = 4;
    public static final int ACTIVECOUNT_FIELD_NUMBER = 4;
    private long activeCount_;
    public boolean hasActiveCount() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public long getActiveCount() {
      return activeCount_;
    }
    
    // required int64 minTime = 5;
    public static final int MINTIME_FIELD_NUMBER = 5;
    private long minTime_;
    public boolean hasMinTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public long getMinTime() {
      return minTime_;
    }
    
    // required int64 maxTime = 6;
    public static final int MAXTIME_FIELD_NUMBER = 6;
    private long maxTime_;
    public boolean hasMaxTime() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public long getMaxTime() {
      return maxTime_;
    }
    
    // required int64 avgTime = 7;
    public static final int AVGTIME_FIELD_NUMBER = 7;
    private long avgTime_;
    public boolean hasAvgTime() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public long getAvgTime() {
      return avgTime_;
    }
    
    // required int64 firstStartTimeMillis = 8;
    public static final int FIRSTSTARTTIMEMILLIS_FIELD_NUMBER = 8;
    private long firstStartTimeMillis_;
    public boolean hasFirstStartTimeMillis() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public long getFirstStartTimeMillis() {
      return firstStartTimeMillis_;
    }
    
    // required int64 lastStopTimeMillis = 9;
    public static final int LASTSTOPTIMEMILLIS_FIELD_NUMBER = 9;
    private long lastStopTimeMillis_;
    public boolean hasLastStopTimeMillis() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public long getLastStopTimeMillis() {
      return lastStopTimeMillis_;
    }
    
    private void initFields() {
      actionType_ = "";
      count_ = 0L;
      errorCount_ = 0L;
      activeCount_ = 0L;
      minTime_ = 0L;
      maxTime_ = 0L;
      avgTime_ = 0L;
      firstStartTimeMillis_ = 0L;
      lastStopTimeMillis_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasActionType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasErrorCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasActiveCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMinTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMaxTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAvgTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFirstStartTimeMillis()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLastStopTimeMillis()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getActionTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, count_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, errorCount_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, activeCount_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, minTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, maxTime_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt64(7, avgTime_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt64(8, firstStartTimeMillis_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt64(9, lastStopTimeMillis_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getActionTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, count_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, errorCount_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, activeCount_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, minTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, maxTime_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, avgTime_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, firstStartTimeMillis_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, lastStopTimeMillis_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.ugcs.ucs.proto.ProfilerProto.ActionSummary parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ugcs.ucs.proto.ProfilerProto.ActionSummary parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ugcs.ucs.proto.ProfilerProto.ActionSummary parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ugcs.ucs.proto.ProfilerProto.ActionSummary parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ugcs.ucs.proto.ProfilerProto.ActionSummary parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ugcs.ucs.proto.ProfilerProto.ActionSummary parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.ugcs.ucs.proto.ProfilerProto.ActionSummary parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ugcs.ucs.proto.ProfilerProto.ActionSummary parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ugcs.ucs.proto.ProfilerProto.ActionSummary parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ugcs.ucs.proto.ProfilerProto.ActionSummary parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ugcs.ucs.proto.ProfilerProto.ActionSummary prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.ugcs.ucs.proto.ProfilerProto.ActionSummaryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ugcs.ucs.proto.ProfilerProto.internal_static_ActionSummary_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ugcs.ucs.proto.ProfilerProto.internal_static_ActionSummary_fieldAccessorTable;
      }
      
      // Construct using com.ugcs.ucs.proto.ProfilerProto.ActionSummary.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        actionType_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        count_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        errorCount_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        activeCount_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        minTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        maxTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        avgTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        firstStartTimeMillis_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        lastStopTimeMillis_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ugcs.ucs.proto.ProfilerProto.ActionSummary.getDescriptor();
      }
      
      public com.ugcs.ucs.proto.ProfilerProto.ActionSummary getDefaultInstanceForType() {
        return com.ugcs.ucs.proto.ProfilerProto.ActionSummary.getDefaultInstance();
      }
      
      public com.ugcs.ucs.proto.ProfilerProto.ActionSummary build() {
        com.ugcs.ucs.proto.ProfilerProto.ActionSummary result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.ugcs.ucs.proto.ProfilerProto.ActionSummary buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.ugcs.ucs.proto.ProfilerProto.ActionSummary result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.ugcs.ucs.proto.ProfilerProto.ActionSummary buildPartial() {
        com.ugcs.ucs.proto.ProfilerProto.ActionSummary result = new com.ugcs.ucs.proto.ProfilerProto.ActionSummary(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.actionType_ = actionType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.count_ = count_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.errorCount_ = errorCount_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.activeCount_ = activeCount_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.minTime_ = minTime_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.maxTime_ = maxTime_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.avgTime_ = avgTime_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.firstStartTimeMillis_ = firstStartTimeMillis_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.lastStopTimeMillis_ = lastStopTimeMillis_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ugcs.ucs.proto.ProfilerProto.ActionSummary) {
          return mergeFrom((com.ugcs.ucs.proto.ProfilerProto.ActionSummary)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.ugcs.ucs.proto.ProfilerProto.ActionSummary other) {
        if (other == com.ugcs.ucs.proto.ProfilerProto.ActionSummary.getDefaultInstance()) return this;
        if (other.hasActionType()) {
          setActionType(other.getActionType());
        }
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        if (other.hasErrorCount()) {
          setErrorCount(other.getErrorCount());
        }
        if (other.hasActiveCount()) {
          setActiveCount(other.getActiveCount());
        }
        if (other.hasMinTime()) {
          setMinTime(other.getMinTime());
        }
        if (other.hasMaxTime()) {
          setMaxTime(other.getMaxTime());
        }
        if (other.hasAvgTime()) {
          setAvgTime(other.getAvgTime());
        }
        if (other.hasFirstStartTimeMillis()) {
          setFirstStartTimeMillis(other.getFirstStartTimeMillis());
        }
        if (other.hasLastStopTimeMillis()) {
          setLastStopTimeMillis(other.getLastStopTimeMillis());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasActionType()) {
          
          return false;
        }
        if (!hasCount()) {
          
          return false;
        }
        if (!hasErrorCount()) {
          
          return false;
        }
        if (!hasActiveCount()) {
          
          return false;
        }
        if (!hasMinTime()) {
          
          return false;
        }
        if (!hasMaxTime()) {
          
          return false;
        }
        if (!hasAvgTime()) {
          
          return false;
        }
        if (!hasFirstStartTimeMillis()) {
          
          return false;
        }
        if (!hasLastStopTimeMillis()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              actionType_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              count_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              errorCount_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              activeCount_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              minTime_ = input.readInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              maxTime_ = input.readInt64();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              avgTime_ = input.readInt64();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              firstStartTimeMillis_ = input.readInt64();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              lastStopTimeMillis_ = input.readInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string actionType = 1;
      private java.lang.Object actionType_ = "";
      public boolean hasActionType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getActionType() {
        java.lang.Object ref = actionType_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          actionType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setActionType(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        actionType_ = value;
        onChanged();
        return this;
      }
      public Builder clearActionType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        actionType_ = getDefaultInstance().getActionType();
        onChanged();
        return this;
      }
      void setActionType(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        actionType_ = value;
        onChanged();
      }
      
      // required int64 count = 2;
      private long count_ ;
      public boolean hasCount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getCount() {
        return count_;
      }
      public Builder setCount(long value) {
        bitField0_ |= 0x00000002;
        count_ = value;
        onChanged();
        return this;
      }
      public Builder clearCount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        count_ = 0L;
        onChanged();
        return this;
      }
      
      // required int64 errorCount = 3;
      private long errorCount_ ;
      public boolean hasErrorCount() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getErrorCount() {
        return errorCount_;
      }
      public Builder setErrorCount(long value) {
        bitField0_ |= 0x00000004;
        errorCount_ = value;
        onChanged();
        return this;
      }
      public Builder clearErrorCount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        errorCount_ = 0L;
        onChanged();
        return this;
      }
      
      // required int64 activeCount = 4;
      private long activeCount_ ;
      public boolean hasActiveCount() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public long getActiveCount() {
        return activeCount_;
      }
      public Builder setActiveCount(long value) {
        bitField0_ |= 0x00000008;
        activeCount_ = value;
        onChanged();
        return this;
      }
      public Builder clearActiveCount() {
        bitField0_ = (bitField0_ & ~0x00000008);
        activeCount_ = 0L;
        onChanged();
        return this;
      }
      
      // required int64 minTime = 5;
      private long minTime_ ;
      public boolean hasMinTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public long getMinTime() {
        return minTime_;
      }
      public Builder setMinTime(long value) {
        bitField0_ |= 0x00000010;
        minTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearMinTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        minTime_ = 0L;
        onChanged();
        return this;
      }
      
      // required int64 maxTime = 6;
      private long maxTime_ ;
      public boolean hasMaxTime() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public long getMaxTime() {
        return maxTime_;
      }
      public Builder setMaxTime(long value) {
        bitField0_ |= 0x00000020;
        maxTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearMaxTime() {
        bitField0_ = (bitField0_ & ~0x00000020);
        maxTime_ = 0L;
        onChanged();
        return this;
      }
      
      // required int64 avgTime = 7;
      private long avgTime_ ;
      public boolean hasAvgTime() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public long getAvgTime() {
        return avgTime_;
      }
      public Builder setAvgTime(long value) {
        bitField0_ |= 0x00000040;
        avgTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearAvgTime() {
        bitField0_ = (bitField0_ & ~0x00000040);
        avgTime_ = 0L;
        onChanged();
        return this;
      }
      
      // required int64 firstStartTimeMillis = 8;
      private long firstStartTimeMillis_ ;
      public boolean hasFirstStartTimeMillis() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public long getFirstStartTimeMillis() {
        return firstStartTimeMillis_;
      }
      public Builder setFirstStartTimeMillis(long value) {
        bitField0_ |= 0x00000080;
        firstStartTimeMillis_ = value;
        onChanged();
        return this;
      }
      public Builder clearFirstStartTimeMillis() {
        bitField0_ = (bitField0_ & ~0x00000080);
        firstStartTimeMillis_ = 0L;
        onChanged();
        return this;
      }
      
      // required int64 lastStopTimeMillis = 9;
      private long lastStopTimeMillis_ ;
      public boolean hasLastStopTimeMillis() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public long getLastStopTimeMillis() {
        return lastStopTimeMillis_;
      }
      public Builder setLastStopTimeMillis(long value) {
        bitField0_ |= 0x00000100;
        lastStopTimeMillis_ = value;
        onChanged();
        return this;
      }
      public Builder clearLastStopTimeMillis() {
        bitField0_ = (bitField0_ & ~0x00000100);
        lastStopTimeMillis_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ActionSummary)
    }
    
    static {
      defaultInstance = new ActionSummary(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ActionSummary)
  }
  
  public interface ActionSummaryRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  public static final class ActionSummaryRequest extends
      com.google.protobuf.GeneratedMessage
      implements ActionSummaryRequestOrBuilder {
    // Use ActionSummaryRequest.newBuilder() to construct.
    private ActionSummaryRequest(Builder builder) {
      super(builder);
    }
    private ActionSummaryRequest(boolean noInit) {}
    
    private static final ActionSummaryRequest defaultInstance;
    public static ActionSummaryRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public ActionSummaryRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ugcs.ucs.proto.ProfilerProto.internal_static_ActionSummaryRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ugcs.ucs.proto.ProfilerProto.internal_static_ActionSummaryRequest_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.ugcs.ucs.proto.ProfilerProto.ActionSummaryRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ugcs.ucs.proto.ProfilerProto.ActionSummaryRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ugcs.ucs.proto.ProfilerProto.ActionSummaryRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ugcs.ucs.proto.ProfilerProto.ActionSummaryRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ugcs.ucs.proto.ProfilerProto.ActionSummaryRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ugcs.ucs.proto.ProfilerProto.ActionSummaryRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.ugcs.ucs.proto.ProfilerProto.ActionSummaryRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ugcs.ucs.proto.ProfilerProto.ActionSummaryRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ugcs.ucs.proto.ProfilerProto.ActionSummaryRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ugcs.ucs.proto.ProfilerProto.ActionSummaryRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ugcs.ucs.proto.ProfilerProto.ActionSummaryRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.ugcs.ucs.proto.ProfilerProto.ActionSummaryRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ugcs.ucs.proto.ProfilerProto.internal_static_ActionSummaryRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ugcs.ucs.proto.ProfilerProto.internal_static_ActionSummaryRequest_fieldAccessorTable;
      }
      
      // Construct using com.ugcs.ucs.proto.ProfilerProto.ActionSummaryRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ugcs.ucs.proto.ProfilerProto.ActionSummaryRequest.getDescriptor();
      }
      
      public com.ugcs.ucs.proto.ProfilerProto.ActionSummaryRequest getDefaultInstanceForType() {
        return com.ugcs.ucs.proto.ProfilerProto.ActionSummaryRequest.getDefaultInstance();
      }
      
      public com.ugcs.ucs.proto.ProfilerProto.ActionSummaryRequest build() {
        com.ugcs.ucs.proto.ProfilerProto.ActionSummaryRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.ugcs.ucs.proto.ProfilerProto.ActionSummaryRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.ugcs.ucs.proto.ProfilerProto.ActionSummaryRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.ugcs.ucs.proto.ProfilerProto.ActionSummaryRequest buildPartial() {
        com.ugcs.ucs.proto.ProfilerProto.ActionSummaryRequest result = new com.ugcs.ucs.proto.ProfilerProto.ActionSummaryRequest(this);
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ugcs.ucs.proto.ProfilerProto.ActionSummaryRequest) {
          return mergeFrom((com.ugcs.ucs.proto.ProfilerProto.ActionSummaryRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.ugcs.ucs.proto.ProfilerProto.ActionSummaryRequest other) {
        if (other == com.ugcs.ucs.proto.ProfilerProto.ActionSummaryRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:ActionSummaryRequest)
    }
    
    static {
      defaultInstance = new ActionSummaryRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ActionSummaryRequest)
  }
  
  public interface ActionSummaryResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .ActionSummary summaries = 1;
    java.util.List<com.ugcs.ucs.proto.ProfilerProto.ActionSummary> 
        getSummariesList();
    com.ugcs.ucs.proto.ProfilerProto.ActionSummary getSummaries(int index);
    int getSummariesCount();
    java.util.List<? extends com.ugcs.ucs.proto.ProfilerProto.ActionSummaryOrBuilder> 
        getSummariesOrBuilderList();
    com.ugcs.ucs.proto.ProfilerProto.ActionSummaryOrBuilder getSummariesOrBuilder(
        int index);
    
    // optional int32 coma = 2 [default = 0];
    boolean hasComa();
    int getComa();
  }
  public static final class ActionSummaryResponse extends
      com.google.protobuf.GeneratedMessage
      implements ActionSummaryResponseOrBuilder {
    // Use ActionSummaryResponse.newBuilder() to construct.
    private ActionSummaryResponse(Builder builder) {
      super(builder);
    }
    private ActionSummaryResponse(boolean noInit) {}
    
    private static final ActionSummaryResponse defaultInstance;
    public static ActionSummaryResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public ActionSummaryResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ugcs.ucs.proto.ProfilerProto.internal_static_ActionSummaryResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ugcs.ucs.proto.ProfilerProto.internal_static_ActionSummaryResponse_fieldAccessorTable;
    }
    
    private int bitField0_;
    // repeated .ActionSummary summaries = 1;
    public static final int SUMMARIES_FIELD_NUMBER = 1;
    private java.util.List<com.ugcs.ucs.proto.ProfilerProto.ActionSummary> summaries_;
    public java.util.List<com.ugcs.ucs.proto.ProfilerProto.ActionSummary> getSummariesList() {
      return summaries_;
    }
    public java.util.List<? extends com.ugcs.ucs.proto.ProfilerProto.ActionSummaryOrBuilder> 
        getSummariesOrBuilderList() {
      return summaries_;
    }
    public int getSummariesCount() {
      return summaries_.size();
    }
    public com.ugcs.ucs.proto.ProfilerProto.ActionSummary getSummaries(int index) {
      return summaries_.get(index);
    }
    public com.ugcs.ucs.proto.ProfilerProto.ActionSummaryOrBuilder getSummariesOrBuilder(
        int index) {
      return summaries_.get(index);
    }
    
    // optional int32 coma = 2 [default = 0];
    public static final int COMA_FIELD_NUMBER = 2;
    private int coma_;
    public boolean hasComa() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getComa() {
      return coma_;
    }
    
    private void initFields() {
      summaries_ = java.util.Collections.emptyList();
      coma_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getSummariesCount(); i++) {
        if (!getSummaries(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < summaries_.size(); i++) {
        output.writeMessage(1, summaries_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(2, coma_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < summaries_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, summaries_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, coma_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.ugcs.ucs.proto.ProfilerProto.ActionSummaryResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ugcs.ucs.proto.ProfilerProto.ActionSummaryResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ugcs.ucs.proto.ProfilerProto.ActionSummaryResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ugcs.ucs.proto.ProfilerProto.ActionSummaryResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ugcs.ucs.proto.ProfilerProto.ActionSummaryResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ugcs.ucs.proto.ProfilerProto.ActionSummaryResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.ugcs.ucs.proto.ProfilerProto.ActionSummaryResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ugcs.ucs.proto.ProfilerProto.ActionSummaryResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ugcs.ucs.proto.ProfilerProto.ActionSummaryResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ugcs.ucs.proto.ProfilerProto.ActionSummaryResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ugcs.ucs.proto.ProfilerProto.ActionSummaryResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.ugcs.ucs.proto.ProfilerProto.ActionSummaryResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ugcs.ucs.proto.ProfilerProto.internal_static_ActionSummaryResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ugcs.ucs.proto.ProfilerProto.internal_static_ActionSummaryResponse_fieldAccessorTable;
      }
      
      // Construct using com.ugcs.ucs.proto.ProfilerProto.ActionSummaryResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSummariesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (summariesBuilder_ == null) {
          summaries_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          summariesBuilder_.clear();
        }
        coma_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ugcs.ucs.proto.ProfilerProto.ActionSummaryResponse.getDescriptor();
      }
      
      public com.ugcs.ucs.proto.ProfilerProto.ActionSummaryResponse getDefaultInstanceForType() {
        return com.ugcs.ucs.proto.ProfilerProto.ActionSummaryResponse.getDefaultInstance();
      }
      
      public com.ugcs.ucs.proto.ProfilerProto.ActionSummaryResponse build() {
        com.ugcs.ucs.proto.ProfilerProto.ActionSummaryResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.ugcs.ucs.proto.ProfilerProto.ActionSummaryResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.ugcs.ucs.proto.ProfilerProto.ActionSummaryResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.ugcs.ucs.proto.ProfilerProto.ActionSummaryResponse buildPartial() {
        com.ugcs.ucs.proto.ProfilerProto.ActionSummaryResponse result = new com.ugcs.ucs.proto.ProfilerProto.ActionSummaryResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (summariesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            summaries_ = java.util.Collections.unmodifiableList(summaries_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.summaries_ = summaries_;
        } else {
          result.summaries_ = summariesBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.coma_ = coma_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ugcs.ucs.proto.ProfilerProto.ActionSummaryResponse) {
          return mergeFrom((com.ugcs.ucs.proto.ProfilerProto.ActionSummaryResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.ugcs.ucs.proto.ProfilerProto.ActionSummaryResponse other) {
        if (other == com.ugcs.ucs.proto.ProfilerProto.ActionSummaryResponse.getDefaultInstance()) return this;
        if (summariesBuilder_ == null) {
          if (!other.summaries_.isEmpty()) {
            if (summaries_.isEmpty()) {
              summaries_ = other.summaries_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSummariesIsMutable();
              summaries_.addAll(other.summaries_);
            }
            onChanged();
          }
        } else {
          if (!other.summaries_.isEmpty()) {
            if (summariesBuilder_.isEmpty()) {
              summariesBuilder_.dispose();
              summariesBuilder_ = null;
              summaries_ = other.summaries_;
              bitField0_ = (bitField0_ & ~0x00000001);
              summariesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSummariesFieldBuilder() : null;
            } else {
              summariesBuilder_.addAllMessages(other.summaries_);
            }
          }
        }
        if (other.hasComa()) {
          setComa(other.getComa());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getSummariesCount(); i++) {
          if (!getSummaries(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.ugcs.ucs.proto.ProfilerProto.ActionSummary.Builder subBuilder = com.ugcs.ucs.proto.ProfilerProto.ActionSummary.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addSummaries(subBuilder.buildPartial());
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              coma_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .ActionSummary summaries = 1;
      private java.util.List<com.ugcs.ucs.proto.ProfilerProto.ActionSummary> summaries_ =
        java.util.Collections.emptyList();
      private void ensureSummariesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          summaries_ = new java.util.ArrayList<com.ugcs.ucs.proto.ProfilerProto.ActionSummary>(summaries_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.ugcs.ucs.proto.ProfilerProto.ActionSummary, com.ugcs.ucs.proto.ProfilerProto.ActionSummary.Builder, com.ugcs.ucs.proto.ProfilerProto.ActionSummaryOrBuilder> summariesBuilder_;
      
      public java.util.List<com.ugcs.ucs.proto.ProfilerProto.ActionSummary> getSummariesList() {
        if (summariesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(summaries_);
        } else {
          return summariesBuilder_.getMessageList();
        }
      }
      public int getSummariesCount() {
        if (summariesBuilder_ == null) {
          return summaries_.size();
        } else {
          return summariesBuilder_.getCount();
        }
      }
      public com.ugcs.ucs.proto.ProfilerProto.ActionSummary getSummaries(int index) {
        if (summariesBuilder_ == null) {
          return summaries_.get(index);
        } else {
          return summariesBuilder_.getMessage(index);
        }
      }
      public Builder setSummaries(
          int index, com.ugcs.ucs.proto.ProfilerProto.ActionSummary value) {
        if (summariesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSummariesIsMutable();
          summaries_.set(index, value);
          onChanged();
        } else {
          summariesBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setSummaries(
          int index, com.ugcs.ucs.proto.ProfilerProto.ActionSummary.Builder builderForValue) {
        if (summariesBuilder_ == null) {
          ensureSummariesIsMutable();
          summaries_.set(index, builderForValue.build());
          onChanged();
        } else {
          summariesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addSummaries(com.ugcs.ucs.proto.ProfilerProto.ActionSummary value) {
        if (summariesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSummariesIsMutable();
          summaries_.add(value);
          onChanged();
        } else {
          summariesBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addSummaries(
          int index, com.ugcs.ucs.proto.ProfilerProto.ActionSummary value) {
        if (summariesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSummariesIsMutable();
          summaries_.add(index, value);
          onChanged();
        } else {
          summariesBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addSummaries(
          com.ugcs.ucs.proto.ProfilerProto.ActionSummary.Builder builderForValue) {
        if (summariesBuilder_ == null) {
          ensureSummariesIsMutable();
          summaries_.add(builderForValue.build());
          onChanged();
        } else {
          summariesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addSummaries(
          int index, com.ugcs.ucs.proto.ProfilerProto.ActionSummary.Builder builderForValue) {
        if (summariesBuilder_ == null) {
          ensureSummariesIsMutable();
          summaries_.add(index, builderForValue.build());
          onChanged();
        } else {
          summariesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllSummaries(
          java.lang.Iterable<? extends com.ugcs.ucs.proto.ProfilerProto.ActionSummary> values) {
        if (summariesBuilder_ == null) {
          ensureSummariesIsMutable();
          super.addAll(values, summaries_);
          onChanged();
        } else {
          summariesBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearSummaries() {
        if (summariesBuilder_ == null) {
          summaries_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          summariesBuilder_.clear();
        }
        return this;
      }
      public Builder removeSummaries(int index) {
        if (summariesBuilder_ == null) {
          ensureSummariesIsMutable();
          summaries_.remove(index);
          onChanged();
        } else {
          summariesBuilder_.remove(index);
        }
        return this;
      }
      public com.ugcs.ucs.proto.ProfilerProto.ActionSummary.Builder getSummariesBuilder(
          int index) {
        return getSummariesFieldBuilder().getBuilder(index);
      }
      public com.ugcs.ucs.proto.ProfilerProto.ActionSummaryOrBuilder getSummariesOrBuilder(
          int index) {
        if (summariesBuilder_ == null) {
          return summaries_.get(index);  } else {
          return summariesBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.ugcs.ucs.proto.ProfilerProto.ActionSummaryOrBuilder> 
           getSummariesOrBuilderList() {
        if (summariesBuilder_ != null) {
          return summariesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(summaries_);
        }
      }
      public com.ugcs.ucs.proto.ProfilerProto.ActionSummary.Builder addSummariesBuilder() {
        return getSummariesFieldBuilder().addBuilder(
            com.ugcs.ucs.proto.ProfilerProto.ActionSummary.getDefaultInstance());
      }
      public com.ugcs.ucs.proto.ProfilerProto.ActionSummary.Builder addSummariesBuilder(
          int index) {
        return getSummariesFieldBuilder().addBuilder(
            index, com.ugcs.ucs.proto.ProfilerProto.ActionSummary.getDefaultInstance());
      }
      public java.util.List<com.ugcs.ucs.proto.ProfilerProto.ActionSummary.Builder> 
           getSummariesBuilderList() {
        return getSummariesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.ugcs.ucs.proto.ProfilerProto.ActionSummary, com.ugcs.ucs.proto.ProfilerProto.ActionSummary.Builder, com.ugcs.ucs.proto.ProfilerProto.ActionSummaryOrBuilder> 
          getSummariesFieldBuilder() {
        if (summariesBuilder_ == null) {
          summariesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.ugcs.ucs.proto.ProfilerProto.ActionSummary, com.ugcs.ucs.proto.ProfilerProto.ActionSummary.Builder, com.ugcs.ucs.proto.ProfilerProto.ActionSummaryOrBuilder>(
                  summaries_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          summaries_ = null;
        }
        return summariesBuilder_;
      }
      
      // optional int32 coma = 2 [default = 0];
      private int coma_ ;
      public boolean hasComa() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getComa() {
        return coma_;
      }
      public Builder setComa(int value) {
        bitField0_ |= 0x00000002;
        coma_ = value;
        onChanged();
        return this;
      }
      public Builder clearComa() {
        bitField0_ = (bitField0_ & ~0x00000002);
        coma_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ActionSummaryResponse)
    }
    
    static {
      defaultInstance = new ActionSummaryResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ActionSummaryResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ActionSummary_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ActionSummary_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ActionSummaryRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ActionSummaryRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ActionSummaryResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ActionSummaryResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Profiler.proto\"\310\001\n\rActionSummary\022\022\n\nac" +
      "tionType\030\001 \002(\t\022\r\n\005count\030\002 \002(\003\022\022\n\nerrorCo" +
      "unt\030\003 \002(\003\022\023\n\013activeCount\030\004 \002(\003\022\017\n\007minTim" +
      "e\030\005 \002(\003\022\017\n\007maxTime\030\006 \002(\003\022\017\n\007avgTime\030\007 \002(" +
      "\003\022\034\n\024firstStartTimeMillis\030\010 \002(\003\022\032\n\022lastS" +
      "topTimeMillis\030\t \002(\003\"\026\n\024ActionSummaryRequ" +
      "est\"K\n\025ActionSummaryResponse\022!\n\tsummarie" +
      "s\030\001 \003(\0132\016.ActionSummary\022\017\n\004coma\030\002 \001(\005:\0010" +
      "B#\n\022com.ugcs.ucs.protoB\rProfilerProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ActionSummary_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ActionSummary_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ActionSummary_descriptor,
              new java.lang.String[] { "ActionType", "Count", "ErrorCount", "ActiveCount", "MinTime", "MaxTime", "AvgTime", "FirstStartTimeMillis", "LastStopTimeMillis", },
              com.ugcs.ucs.proto.ProfilerProto.ActionSummary.class,
              com.ugcs.ucs.proto.ProfilerProto.ActionSummary.Builder.class);
          internal_static_ActionSummaryRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ActionSummaryRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ActionSummaryRequest_descriptor,
              new java.lang.String[] { },
              com.ugcs.ucs.proto.ProfilerProto.ActionSummaryRequest.class,
              com.ugcs.ucs.proto.ProfilerProto.ActionSummaryRequest.Builder.class);
          internal_static_ActionSummaryResponse_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_ActionSummaryResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ActionSummaryResponse_descriptor,
              new java.lang.String[] { "Summaries", "Coma", },
              com.ugcs.ucs.proto.ProfilerProto.ActionSummaryResponse.class,
              com.ugcs.ucs.proto.ProfilerProto.ActionSummaryResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
